"""empty message

Revision ID: 349c8adade14
Revises: 8ffe73c4df6f
Create Date: 2025-04-15 20:52:10.945310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '349c8adade14'
down_revision = '8ffe73c4df6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=256), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', mysql.VARCHAR(length=1000), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
